spring.application.name=Redbus

# ==============================
# Database Configuration (MySQL 8)
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/db_name?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=db_username
spring.datasource.password=db_passwrod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==============================
# Thymeleaf Config
# ==============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false